name: Release to Nuget

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/libraries

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    # Praticis.Framework.Bus.Abstractions
    - name: echo "Create ${{env.package}} Package"
      env:
        package: Praticis.Framwork.Bus.Abstractions
      run: dotnet pack -c Release /p:Version=${{github.event.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/Praticis/Framework/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ${{env.working-directory}}/${{env.package}}
    - name: echo "Archive ${{env.package}} Package"
      uses: actions/upload-artifact@v1
      with:
        name: ${{env.package}}
        path: ${{env.working-directory}}/${{env.package}}/src/bin/Release/${{env.package}}.${{ github.event.release.tag_name }}.nupkg
      env:
        package: Praticis.Framwork.Bus.Abstractions
    # Praticis.Framework.Bus
    - name: Create Praticis.Framework.Bus Package
      run: dotnet pack -c Release /p:Version=${{github.event.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/Praticis/Framework/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ${{env.working-directory}}/Praticis.Framework.Bus
    - name: Archive Praticis.Framework.Bus Package
      uses: actions/upload-artifact@v1
      with:
        name: Praticis.Framework.Bus
        path: ${{env.working-directory}}/Praticis.Framework.Bus/src/bin/Release/Praticis.Framework.Bus.${{ github.event.release.tag_name }}.nupkg
    - name: Publish Nuget Packages
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json --no-symbols true
